# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [7]:
# Import torch
import torch

# Create random tensor
X = torch.rand(size=(7, 7))
print(X, X.shape)


tensor([[0.5917, 0.7878, 0.0155, 0.9627, 0.0905, 0.8199, 0.6592],
        [0.1155, 0.5757, 0.7684, 0.0509, 0.2452, 0.0152, 0.0148],
        [0.2550, 0.4238, 0.7342, 0.7923, 0.5931, 0.7782, 0.9335],
        [0.7675, 0.7603, 0.5421, 0.0010, 0.4256, 0.5253, 0.1345],
        [0.0517, 0.7667, 0.8942, 0.4850, 0.1680, 0.9267, 0.9501],
        [0.1213, 0.1251, 0.4955, 0.6349, 0.7361, 0.2976, 0.9142],
        [0.0998, 0.4398, 0.5346, 0.0130, 0.5310, 0.4812, 0.9742]]) torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
print(Y, Y.shape)

# Perform matrix multiplication 
Z = torch.mm(X, Y.T)
print(Z, Z.shape)

tensor([[0.6918, 0.6042, 0.3186, 0.4441, 0.6234, 0.5359, 0.4229]]) torch.Size([1, 7])
tensor([[2.0925],
        [0.8625],
        [2.1999],
        [1.7672],
        [2.0025],
        [1.6045],
        [1.5117]]) torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.mm(X, Y.T)
print(Z, Z.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)
torch.cuda.is_available()

False


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
shape = (2, 3)
tensor_1 = torch.rand(size=shape).to(device=device)
tensor_2 = torch.rand(size=shape).to(device=device)
print(tensor_1, tensor_2)

Device: mps
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='mps:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='mps:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
tensor_3 = torch.mm(tensor_1, tensor_2.T)
print(tensor_3, tensor_3.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
print(f"max element of last tensor: {torch.max(tensor_3)}")

# Find min
print(f"min element of last tensor: {torch.min(tensor_3)}")


max element of last tensor: 0.5617256760597229
min element of last tensor: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
print(f"max index of last tensor: {torch.argmax(tensor_3)}")

# Find arg min
print(f"min index of last tensor: {torch.argmin(tensor_3)}")


max index of last tensor: 3
min index of last tensor: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(size=(1, 1, 1, 10))
print(tensor, tensor.shape)

# Remove single dimensions
squeezed_tensor = tensor.squeeze()
print(squeezed_tensor, squeezed_tensor.shape)

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
